# This is a basic workflow to help you get started with Actions

name: Getting Started

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-on-ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: step1 display the disk space
        run: df
        
      - name: Step2 - checout the code to make the job access it.
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v4
        
      - name: Step3 - setup java jdk
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: build maven project
        run: mvn -B package --file pom.xml

      - name: create cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{runner.os}}-m2-${{hashFiles('**/pom.xml')}}
          restore-keys: ${{runner.os}}-m2
            
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sh ./github-actions.sh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Check Single Line command runs.

      - name: Final Step, display the display space
        run: df
        
  build-on-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: step1 display the disk space
        run: ls
        
      - name: Step2 - checout the code to make the job access it.
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v4
        
      - name: Step3 - setup java jdk
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      # Runs a single command using the runners shell
      - name: check windows execution policy
        run: Get-ExecutionPolicy

      # Runs a set of commands using the runners shell
      - name: Envir
        run: |
          echo Display all environment variables in windows
          env

      - name: Final Step, display the display space
        run: ls
